### PR TITLE
Add a date hierarchy to the impression admin views

### PR DESCRIPTION
**Pull request by davidfischer**

### CODE REVIEW

**Comment by ericholscher** [comment]
This seems to perform badly in prod from my testing. Appears to hang up on `SELECT DISTINCT DATE_TRUNC('day', "adserver_offer"."date") AS "datefield" FROM
 "adserver_offer" WHERE "adserver_offer"."date" IS NOT NULL ORDER BY "datefield" ASC`

**Review by ericholscher — CHANGES_REQUESTED** [review]
Unless you found different, this seemed to break the admin pages locally when I tried it. :/

**Comment by davidfischer** [comment]
I think you're right. There's possibly some options here but maybe nothing out of the box. I'm going to give it a quick look and close this out if I don't find a good option.

**Comment by davidfischer** [comment]
Here's [an article](https://hakibenita.medium.com/scaling-django-admin-date-hierarchy-85c8e441dd4c) outlining some of the trade-offs. I'm fine closing this out for now.

**Pull request closed without merging**
