### PR TITLE
Order the Ad admin by created date, not slug

### PR DESCRIPTION
**Pull request by ericholscher**
We should probably change the sorting on this model in general,
but I'm not sure why it's `ordering = ("slug", "-live")` so I didn't mess with it.

### CODE REVIEW

**Comment by davidfischer** [comment]
The edit in this PR refers to the Advertiser model but your comment refers to the Advertisement model. I don't think there's a good reason about the ad ordering especially since slug has a unique key on it (I think it didn't in the old system).

**Comment by ericholscher** [comment]
Ugh, I seem to be incapable of editing the proper admin for Adverisements heh

**Comment by ericholscher** [comment]
@davidfischer the creation date should be deterministic, no?

**Comment by davidfischer** [comment]
> @davidfischer the creation date should be deterministic, no?

No it isn't. Two objects can have the same create date. Basically, Django does some odd things in cases where the order isn't perfectly deterministic: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.ordering

**Pull request merged**
