### PR TITLE
Update exclude list

### PR DESCRIPTION
**Pull request by davidfischer**

### CODE REVIEW

**Review by ericholscher — COMMENTED** [review]
Should `IN` be added to another region?

**Comment by davidfischer** [comment]
I don't think so. Advertisers do want it but they say that explicitly when they do.

**Comment by ericholscher** [comment]
It just feels weird to have it outside of a region list for reporting. Generally we want each of the countries to be in one of the lists of regions, otherwise we don't know where to include it in reports.

**Comment by davidfischer** [comment]
I think you're correct. I'll add a separate South Asia region.

**Review by ericholscher — APPROVED** [review]
💯

**Pull request merged**
