### PR TITLE
Add publisher query parameter to ad clicks

### PR DESCRIPTION
**Pull request by davidfischer**
This appends a publisher query parameter `ea-publisher=<publisher-slug>` to ad click redirects.

## Proposed alternative

This does feel a bit like "magic" to me since the advertiser doesn't control it. Could this extra query parameter muck up the analytics that our advertisers are running? Would they prefer it in another variable? Another alternative would be to just document our existing substitution like so:

Screenshot from 2021-03-25 15-49-40

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
I think this is good. 

We should mention this is happening in the help text, instead of asking publishers to use some wonky syntax to add it themselves. That seems way more error prone.

Alternatively, we could have an additional field that is `query param for publisher data` and let advertisers customize this, default to `ea-publisher`, if we're worried they want a different parameter for it. I think this will be fine for now though.

**Comment by davidfischer** [comment]
I added some help text but otherwise this is good to go.

**Comment by ericholscher** [comment]
@davidfischer did you want to only do it when the user hadn't defined it, or just worry about that later?

**Comment by davidfischer** [comment]
I'm on the fence. Just to be clear, you're thinking to only add `ea-publisher` if the user doesn't have `${publisher}` in the URL? I think I'm on board with that but it just feels like a bit of magic.

**Comment by ericholscher** [comment]
Yea -- might be better to just always include it. Easier to understand. I can imagine a case where a subset of flights had a `publisher` and they got weird/missing data.

**Pull request merged**
